version: "3"
services:
#  master:
#    image: joylogics/dpx-master:latest
#    deploy:
#      replicas: 1
#    ports:
#      - "6123:6123"
#    networks:
#      - webnet
  rest:
    image: joylogics/catalogic-dpx-rest-master:latest
    env_file:
     - ./dpx.env
    environment:
#      - DPX_MASTER_HOST=${DPX_MASTER_HOST}
      - _JAVA_OPTIONS=-Dlogging.level.com.catalogic.dpx.rest.commons.DBConn=DEBUG -Dauth.server.public.key.file.path=/key/catalogic.pub
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    volumes:
      - "./opt-apigateway:/key"
      - "./rest-logs:/logs"
    networks:
      - "webnet"
  vplugin-mgr:
    image: joylogics/catalogic-dpx-vplugin-mgr-master:latest
    env_file:
     - ./dpx.env
    environment:
#      - DOCKER_HOST_IP=${DPX_MASTER_HOST}
      - AUTH_SERVER_URL=http://auth:8081
      - SVC_SERVER_URL=http://rest:8080
    deploy:
      replicas: 1
    ports:
      - "8082:8082"
    networks:
      - webnet
  auth:
    image: joylogics/catalogic-dpx-auth-master:latest
    env_file:
     - ./dpx.env
#    environment:
#      - DPX_MASTER_HOST=${DPX_MASTER_HOST}
    deploy:
      replicas: 1
    ports:
      - "8081:8081"
    volumes:
      - "./opt-auth/catalogic.jks:/opt/catalogic.jks"
    networks:
      - webnet
  apigateway:
    image: joylogics/catalogic-dpx-apigateway-master:latest
    environment:
        - zuul_routes_app_url=http://rest:8080/
        - zuul_routes_auth_url=http://auth:8081/
        - zuul_routes_plugin_mgr_url=http://vplugin-mgr:8082/
        - zuul_routes_config_ui_url=http://config-ui:80/
    deploy:
      replicas: 1
    ports:
      - "8085:8085"
    volumes:
      - "./opt-apigateway:/opt"
    networks:
      -  webnet
  config-ui:
    image: joylogics/catalogic-dpx-ui:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    networks:
      - webnet
networks:
      webnet:
