version: "3.7"
services:
  rest:
    image: catalogicsoftware/dpx-rest:${TAG_REST}
    env_file:
     - ./dpx.env
    environment:
      - _JAVA_OPTIONS=-Dlogging.level.com.catalogic.dpx.rest.commons.DBConn=DEBUG -Dauth.server.public.key.file.path=/key/catalogic.pub
      - DPX_MAX_CONNECTIONS_PER_USER=6
      - START_DATE=${START_DATE}
      - START_DATE1=6
    deploy:
      replicas: 2
      update_config:
        failure_action: rollback
    ports:
      - "8080:8080"
    volumes:
      - "./opt-apigateway:/key"
      - "./opt-apigateway:/opt"
    networks:
      - "webnet"
    logging:
      driver: "fluentd"
      options:
        tag: dpx-rest
  vplugin-mgr:
    image: catalogicsoftware/dpx-vplugin-mgr:${TAG_VPLUGIN_MGR}
    env_file:
     - ./dpx.env
     - ./dpx-vplugin-mgr.env
    environment:
      - AUTH_SERVER_URL=http://auth:8081
      - SVC_SERVER_URL=http://rest:8080
      - S3_BUCKET_FOLDER_NAME=released
      - START_DATE=${START_DATE}
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
    healthcheck:
      test: wget -qO- http://localhost:8082/actuator/health | grep -q '"UP"' || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "8082:8082"
    volumes:
      - "./plugins:/app/plugins"
    networks:
      - webnet
    logging:
      driver: "fluentd"
      options:
        tag: dpx-vplugin-mgr
  auth:
    image: catalogicsoftware/dpx-auth:${TAG_AUTH}
    environment:
      - START_DATE=${START_DATE}
    env_file:
     - ./dpx.env
    deploy:
      replicas: 2
      update_config:
        failure_action: rollback
    healthcheck:
#      test: wget -qO- http://localhost:8081/actuator/health | grep -q '"UP"' || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "8081:8081"
    volumes:
      - "./opt-auth/catalogic.jks:/opt/catalogic.jks"
    networks:
      - webnet
    logging:
      driver: "fluentd"
      options:
        tag: dpx-auth
  config-ui:
    image: catalogicsoftware/dpx-ui:${TAG_UI}
    env_file:
     - ./dpx-apigateway.env
     - ./dpx.env
    environment:
      - START_DATE=${START_DATE}
    deploy:
      replicas: 2
      update_config:
        failure_action: rollback
    healthcheck:
      test: wget -qO- http://localhost:8088/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "8088:8088"
    networks:
      - webnet
    logging:
      driver: "fluentd"
      options:
        tag: dpx-config-ui
  apigateway:
    image: catalogicsoftware/dpx-apigateway:${TAG_APIGATEWAY}
    env_file:
     - ./dpx-apigateway.env
     - ./dpx.env
    environment:
        - zuul_routes_app_url=http://rest:8080/
        - zuul_routes_auth_url=http://auth:8081/
        - zuul_routes_plugin_mgr_url=http://vplugin-mgr:8082/
        - zuul_routes_config_ui_url=http://config-ui:8088/
        - SOCKET_TIMEOUT_MILLIS=120000
        - START_DATE=${START_DATE}
    deploy:
      replicas: 2
      update_config:
        failure_action: rollback
    healthcheck:
      test: wget -qO- http://localhost:8085/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "80:8085"
      - "443:443"
    volumes:
      - "./opt-apigateway:/opt"
    networks:
      -  webnet
    logging:
      driver: "fluentd"
      options:
        tag: dpx-apigateway
  fluentd:
    image: fluent/fluentd:v1.4-1
#    environment:
#      - START_DATE=${START_DATE}
    env_file:
     - ./dpx-apigateway.env
     - ./dpx.env
    volumes:
#      - "./config/fluent.conf:/fluentd/etc/fluent.conf"
      - "./stack-logs:/fluentd/log"
    ports:
      - "24224:24224"
    configs:
      - source: fluentd_conf
        target: /fluentd/etc/fluent.conf
    networks:
      - webnet
configs:
  fluentd_conf:
    name: fluentd_conf-${FLUENTD_CONFIG_DIGEST}
    file: ./config/fluent.conf
networks:
    webnet:
