version: "3"
services:
  rest:
    image: joylogics/catalogic-dpx-rest:${TAG_REST}
    env_file:
     - ./dpx.env
    environment:
      - _JAVA_OPTIONS=-Dlogging.level.com.catalogic.dpx.rest.commons.DBConn=DEBUG -Dauth.server.public.key.file.path=/key/catalogic.pub
      - DPX_MAX_CONNECTIONS_PER_USER=6
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    volumes:
      - "./opt-apigateway:/key"
      - "./rest-logs:/logs"
      - "./opt-apigateway:/opt"
    networks:
      - "webnet"
  vplugin-mgr:
    image: joylogics/catalogic-dpx-vplugin-mgr:${TAG_VPLUGIN_MGR}
    env_file:
     - ./dpx.env
     - ./dpx-vplugin-mgr.env
    environment:
      - AUTH_SERVER_URL=http://auth:8081
      - SVC_SERVER_URL=http://rest:8080
      - S3_BUCKET_FOLDER_NAME=released
    deploy:
      replicas: 1
    ports:
      - "8082:8082"
    volumes:
      - "./plugins:/app/plugins"
    networks:
      - webnet
  auth:
    image: joylogics/catalogic-dpx-auth:${TAG_AUTH}
    env_file:
     - ./dpx.env
    deploy:
      replicas: 1
    ports:
      - "8081:8081"
    volumes:
      - "./opt-auth/catalogic.jks:/opt/catalogic.jks"
    networks:
      - webnet
  config-ui:
    image: joylogics/catalogic-dpx-ui:${TAG_UI}
    deploy:
      replicas: 1
    ports:
      - "8083:80"
    networks:
      - webnet
  apigateway:
    image: joylogics/catalogic-dpx-apigateway:${TAG_APIGATEWAY}
    env_file:
     - ./dpx-apigateway.env
    environment:
        - zuul_routes_app_url=http://rest:8080/
        - zuul_routes_auth_url=http://auth:8081/
        - zuul_routes_plugin_mgr_url=http://vplugin-mgr:8082/
        - zuul_routes_config_ui_url=http://config-ui:80/
        - SOCKET_TIMEOUT_MILLIS=120000
    deploy:
      replicas: 1
    ports:
      - "80:8085"
      - "443:443"
    volumes:
      - "./opt-apigateway:/opt"
    networks:
      -  webnet
networks:
    webnet:
